DROP TABLE client IF EXISTS;
DROP TABLE country IF EXISTS;
DROP TABLE city IF EXISTS;
DROP TABLE user_request_log IF EXISTS;

DROP SEQUENCE client_seq IF EXISTS;
DROP SEQUENCE user_seq IF EXISTS;
DROP SEQUENCE city_seq IF EXISTS;
DROP SEQUENCE country_seq IF EXISTS;
DROP SEQUENCE user_req_seq IF EXISTS;


CREATE SEQUENCE client_seq AS INTEGER START WITH 100000;
CREATE SEQUENCE user_seq AS INTEGER START WITH 100000;
CREATE SEQUENCE city_seq AS INTEGER START WITH 100000;
CREATE SEQUENCE country_seq AS INTEGER START WITH 100000;
CREATE SEQUENCE user_req_seq AS INTEGER START WITH 100000;

CREATE TABLE client
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE client_seq PRIMARY KEY,
    name             VARCHAR(255)            NOT NULL,
    city_id          INTEGER                 NOT NULL,
    iin              VARCHAR(12)             NOT NULL,
    birthdate        TIMESTAMP               NOT NULL,
    phone_number     VARCHAR(20)             NOT NULL,
    FOREIGN KEY (city_id) REFERENCES city(id)
);

CREATE TABLE country
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE country_seq PRIMARY KEY,
    code            VARCHAR(10),
    name            VARCHAR(255),
    capital         VARCHAR(255)
);

CREATE TABLE city
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE city_seq PRIMARY KEY,
    code            VARCHAR(10),
    name            VARCHAR(255),
    country_id      INTEGER,
    FOREIGN KEY (country_id) REFERENCES country(id)
);

CREATE TABLE user_request_log
(
    id                  INTEGER GENERATED BY DEFAULT AS SEQUENCE user_req_seq PRIMARY KEY,
    user_id             INTEGER,
    req_datetime        TIMESTAMP NOT NULL,
    req_param           VARCHAR(4000),
    FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE user
(
    id                  INTEGER GENERATED BY DEFAULT AS SEQUENCE user_seq PRIMARY KEY,
    name                VARCHAR(255)
)